version: '3'
services:

  phpfpm:
    build:
      context: docker/phpfpm
    volumes:
      - ./docker/phpfpm/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - .:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    environment:
      SYMFONY_ENV: dev
      COMPOSER_MEMORY_LIMIT: -1
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis

  web:
    image: nginx:stable
    depends_on:
      - phpfpm
    volumes:
      - ./docker/web/local.template:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    ports:
      - 80:80
    links:
      - phpfpm

  mysql:
    image: mysql:8.0.36
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/${MYSQL_CONFIG:-my.cnf}:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      MYSQL_ROOT_HOST: '%'

  redis:
    build: docker/redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"

  #scheduler:
  #  build: docker/scheduler
  #  volumes:
  #    - .:/usr/share/nginx/html
  #    - ./docker/scheduler/crontab:/var/spool/cron/crontabs/www-data
  #  working_dir: /usr/share/nginx/html
  #  depends_on:
  #    - mysql
  #    - redis
  #  links:
  #    - mysql
  #    - redis

  #queue:
  #  build: docker/queue
  #  volumes:
  #    - .:/usr/share/nginx/html
  #    - ./docker/queue/supervisord.conf:/etc/supervisor/supervisord.conf
  #    - ./docker/queue/docker-php-memlimit.ini:/usr/local/etc/php/conf.d/docker-php-memlimit.ini
  #  working_dir: /usr/share/nginx/html
  #  depends_on:
  #    - mysql
  #    - redis
  #  links:
  #    - mysql
  #    - redis
